name: Issue Comment

on:
    issues:
        types:
            - opened
            - reopened

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            # - name: Dump GitHub context
            #   run: echo '${{ toJSON(github.event) }}' | jq
            #   shell: bash
            
            - name: Create comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                  token: ${{ secrets.REPO_SECRET }}
                  issue-number: ${{ github.event.issue.number }}
                  body: |
                      Thank you for creating this issue!
                      
                      I'll get back to you as soon as I can.

                      Have a great day!

                      --

                      *This comment was created automatically.*
                    
                  reactions: '+1'

    comment-with-api:
        runs-on: ubuntu-latest
        steps:
            - name: Create comment with API
              id: create_comment
              run: |
                COMMENT_ID=$(gh api -X POST \
                  /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
                  -f body="$(cat <<EOF
                Comment with API.
                Thank you!
                EOF
                )" \
                  -q '.id')
                echo "comment_id=$COMMENT_ID" >> $GITHUB_ENV
              env:
                GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}
                REPOSITORY: ${{ github.event.repository.name }}
                ISSUE_NUMBER: ${{ github.event.issue.number }}

            - name: Add reaction to comment
              run: |
                gh api -X POST \
                  /repos/${{ github.repository }}/issues/comments/${{ env.comment_id }}/reactions \
                  -f content="+1"
              env:
                GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}
                COMMENT_ID: ${{ env.comment_id }}
